# Generated by Django 3.2.4 on 2021-06-27 14:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stocks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter Stock Name', max_length=200)),
                ('description', models.TextField(help_text='Enter Product Description')),
                ('unitCost', models.FloatField(default=0.0, help_text='Enter Stock Unit Cost')),
                ('unit', models.CharField(help_text='Enter Stock Unit ', max_length=10)),
                ('quantity', models.IntegerField(default=0, help_text='Enter Stock Quantity')),
                ('open', models.FloatField(default=0.0)),
                ('high', models.FloatField(default=0.0)),
                ('low', models.FloatField(default=0.0)),
                ('close', models.FloatField(default=0.0)),
                ('volume', models.IntegerField(default=0)),
                ('symb', models.CharField(help_text='Enter Symbol', max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter User Name', max_length=200)),
                ('username', models.CharField(default='null', help_text='Enter User Name', max_length=200)),
                ('mobile', models.IntegerField(null=True)),
                ('email', models.CharField(max_length=200, null=True)),
                ('password', models.CharField(max_length=10)),
                ('description', models.TextField(help_text='Enter User Description')),
                ('stock_no', models.IntegerField(default=0)),
                ('portfolio_val', models.IntegerField(default=0.0)),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.stocks')),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=0, help_text='Enter Stock Quantity')),
                ('Val', models.FloatField(default=0.0)),
                ('stock', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.stocks')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
